### ISSUE TITLE
Why the strategy of PurpleWave is using all initial probes to attack?

### ISSUE THREAD

**Issue by wzhrj1234** [dgant/PurpleWave#9]
Sorry to bother you. I have a problem about PurpleWave.

As the install.md shows, I use BWAPI 4.1.2 and 32-bit java to run PurpleWave AI. PurpleWave.dll, PurpleWave.jar, run_proxy.bat which are downloaded from AIIDE Starcraft AI competition web are included in the bwapi-data\AI document.  When I use java to run the PurpleWave.jar and start the Starcraft game, the cmd shows " Game ready!". At the beginning of the game, PurpleWave let all initial probes to attack and will not build new probe. There is no double that PurpleWave lose the game. 

This game strategy is very different to the replays of PurpleWave in 2017th Starcraft AI competition. Is there anything I've done wrong here？

**Comment by dgant** [comment]
Hi @wzhrj1234! PurpleWave has multiple strategies. After each game, it saves the results of the game to bwapi-data/write/_v2_history_OPPONENTNAME.csv and uses that to decide what to do in the next game.

In AIIDE 2017, PurpleWave was configured to do a worker rush in its first game against each opponent: https://www.youtube.com/watch?v=wFDoHp1tvV0 . So if you want the AIIDE 2017 version of PurpleWave to do something more interesting, you'll have to let it lose a game. It'll record that result in bwapi-data/write/_v2_history_OPPONENTNAME.csv, then try something different in the next game.

You could also get the latest compiled version of PurpleWave from SSCAIT at https://sscaitournament.com/index.php?action=botDetails&bot=PurpleWave -- it does not default to a worker rush, and is generally much stronger than the AIIDE 2017 version.

**Comment by wzhrj1234** [comment]
@dgant Thank you very much!
